### ISSUE TITLE
import를 모두 소스 루트에 대한 절대경로로 바꿉니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/colorado#10]
현재 `import`는 Jest의 alias 설정 문제 등으로 인해 상대경로를 사용하고 있었는데, 해결할 방법을 최근에야 찾았습니다.

- https://alexjoverm.github.io/2017/10/07/Enhance-Jest-configuration-with-Module-Aliases/

문제는 루트(`<projectRoot>/src`)의 alias로 사용할 이름을 정해야 하는데요, `colorado`로 하자니 임시 명칭이라 애매하고, `app`을 쓰자니 앱이 아니고, `lib`을 쓰자니 외부 라이브러리처럼 보이는 듯도 하네요. 그나마 나아보이는 선택지는 `lib`이긴 한데, 다른 아이디어 있으신가요?

**Comment by limgit** [comment]
그냥 단순하게 `root`는 안되나요? `<projectRoot>/src`의 alias를 원하는거면 `src` 자체도 괜찮다고 봅니다. 혹은 둘이 섞어서 `srcRoot`라거나....

**Comment by JeongHoJeong** [comment]
`root`는 한 번도 본 적 없는 컨벤션이라 걸리지만, `src`는 나쁘진 않겠군요. 다만 alias인데 디렉토리 이름이 겹쳐도 되나 싶은 생각이.. 음.. 뭐 상관 없겠죠..?

**Comment by limgit** [comment]
흠... 저도 그 점이 걸리긴 하네요. 예시로 주신 링크에서 쓴 것처럼 아예 그냥 `@`같은 문자는 안되려나요?

**Comment by limgit** [comment]
아니면 여기서 라이브러리 이름을 정하고 가는 것도 괜찮은 방법일 것 같습니다

**Comment by JeongHoJeong** [comment]
라이브러리 이름을 정하는 것도 깔끔하긴 하겠네요. 흠... 근데 뭔가 코드에 매직스트링이 박히는 기분이라...

`@`도 상당히 괜찮은 아이디어 같습니다. 별 문제 없다면 이쪽을 택하고 싶네요.

**Comment by limgit** [comment]
:+1: 저도 `@` 이 괜찮다고 생각합니다
