### ISSUE TITLE
Scientific pitch notation에서 Pitch로 변환할 방법이 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/colorado#9]
[Scientific pitch notation (Wikipedia)](https://en.wikipedia.org/wiki/Scientific_pitch_notation)

## 제안
- 사용자 편의 측면에서 필수적입니다.
- 현재는 12-TET만을 기준으로 동작해도 충분할 것 같습니다.

```ts
const pitchA3 = new Pitch('A3') // 이렇게?
const pitchA4 = fromSPN('A4') // 혹은 이렇게?

expect(pitchA3).toBeInstanceOf(Pitch)
expect(pitchA3.height).toBe(-12)
```

**Comment by limgit** [comment]
저 개인적으로는 위쪽 방법인 `const pitchA3 = new Pitch('A3')` 쪽이 더 끌리네요

**Comment by JeongHoJeong** [comment]
둘 다 지원하는 방법은 어떻게 생각하시나요? 인터페이스를 헷갈리게 하려나요.

**Comment by limgit** [comment]
음... 둘 다 제공하는것도 방법일 순 있겠지만 내부 구조를 아예 모르는 사용자의 입장을 가정하면 `new Pitch('A3')` 쪽이 더 자연스러운 것 같아서요

**Comment by JeongHoJeong** [comment]
동의합니다. 일단 굳이 처음부터 입구만 늘려놓을 필요는 없겠죠. 첫 번째 안으로 갑시다. 🚀
